### ISSUE TITLE
System.OverflowException When trying to export MCC's mp_masterchief as a COLLADA file

### ISSUE THREAD

**Issue by afairfax** [Gravemind2401/Reclaimer#1]
The following is the console output, I'm just tryinig to get the Halo 3 Spartan, does it look like the problem is on my end?  

Loading map file: C:\Program Files (x86)\Steam\steamapps\common\Halo The Master Chief Collection\halo3\maps\sandbox.map
Loaded map file: C:\Program Files (x86)\Steam\steamapps\common\Halo The Master Chief Collection\halo3\maps\sandbox.map
Loading model: objects\characters\masterchief\mp_masterchief\mp_masterchief.render_model
Loaded model: objects\characters\masterchief\mp_masterchief\mp_masterchief.render_model
Error extracting objects\characters\masterchief\mp_masterchief\mp_masterchief
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Assimp.MemoryHelper.AllocateMemory(Int32 sizeInBytes, Int32 alignment)
   at Assimp.MemoryHelper.ToNativeArray[Managed,Native](Managed[] managedArray, Boolean arrayOfPointers)
   at Assimp.Scene.Assimp.IMarshalable<Assimp.Scene,Assimp.Unmanaged.AiScene>.ToNative(IntPtr thisPtr, AiScene& nativeValue)
   at Assimp.MemoryHelper.ToNativePointer[Managed,Native](Managed managedValue)
   at Assimp.AssimpContext.ExportFile(Scene scene, String fileName, String exportFormatId, PostProcessSteps preProcessing)
   at Reclaimer.Plugins.ModelViewerPlugin.WriteModelFile(IGeometryModel model, String fileName, String formatId)
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IRenderGeometry geometry, String baseDir)
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IIndexItem tag)
   at CallSite.Target(Closure , CallSite , BatchExtractPlugin , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , BatchExtractPlugin , Object )
   at Reclaimer.Plugins.BatchExtractPlugin.Extract(Object tag, ExtractCounter counter)
Extracted 0 tags in 8 seconds with 1 errors.

Thank you so much for what you've done for Halo content creation, I've made a ton of renders with the models I'm able to acquire thanks to you. I really appreciate it a ton! I have a ton of respect for the reverse engineering you do, and have no idea how scientists like you are able to pull it off, it's absolutely incredible. Do you have a social media outlet, like a Twitter, or a Discord? I'd love to follow you, but there are a lot of "Graveminds" out there.

**Comment by Gravemind2401** [comment]
This looks to be happening because the exporter runs out of memory. When you open the model in the model viewer it uses just about all the memory allowed by the app, leaving insufficient memory left to do the export.

Unfortunately there doesn't seem to be much I can do to reduce the memory usage, as the vast majority is being used by the underlying rendering framework as opposed to being used directly by Reclaimer. The only things that seem to make a noticeable difference are scaling down the textures or removing them completely.

To work around this you can right click the tag and select Extract, rather than opening it in the viewer first. You can also try opening it with the Architect viewer instead, as it uses a much more efficient renderer than the default one.

**Comment by afairfax** [comment]
Thank you so much, it worked perfectly!
