### ISSUE TITLE
[MCC Reach] Issue Previewing/Extracting .render_model LOD

### ISSUE THREAD

**Issue by Unordinal** [Gravemind2401/Reclaimer#12]
I'm having an ArgumentNullException when trying to preview or extract .render_models with a `_lod#` suffix from MCC Halo Reach maps.

```
Loading model: levels\shared\decorators\m50_leaf_pilea\m50_leaf_pilea_lod1.render_model
Error loading model: levels\shared\decorators\m50_leaf_pilea\m50_leaf_pilea_lod1.render_model
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Skip[TSource](IEnumerable`1 source, Int32 count)
   at Adjutant.Blam.HaloReach.render_model.CreateInstanceMeshes(GeometryModel model)
   at Adjutant.Blam.HaloReach.render_model.ReadGeometry(Int32 lod)
   at Reclaimer.Controls.ModelViewer.SetLod(Int32 index)
   at Reclaimer.Controls.ModelViewer.LoadGeometry(IRenderGeometry geometry, String fileName)
   at Reclaimer.Plugins.ModelViewerPlugin.DisplayModel(ITabContentHost targetWindow, IRenderGeometry model, String fileName)
Error extracting levels\shared\decorators\m50_leaf_pilea\m50_leaf_pilea_lod1.render_model
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Skip[TSource](IEnumerable`1 source, Int32 count)
   at Adjutant.Blam.HaloReach.render_model.CreateInstanceMeshes(GeometryModel model)
   at Adjutant.Blam.HaloReach.render_model.ReadGeometry(Int32 lod)
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IRenderGeometry geometry, String baseDir)
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IExtractable item)
   at Reclaimer.Plugins.BatchExtractPlugin.Extract(IExtractable item, ExtractCounter counter)
Extracted 0 tags in 1 seconds with 1 errors.
```

**Comment by Gravemind2401** [comment]
These `_lod` models have vertices but they don't actually have any edges. I'm not sure how they are used by the game. The most recent Reclaimer update will now show a specific error message for models with no edges.
