### ISSUE TITLE
Cannot extract Sticky Detonator

### ISSUE THREAD

**Issue by afairfax** [Gravemind2401/Reclaimer#2]
Hullo again! I really appreciate how easy you are to contact. I've been trying to extract the sticky detonator from Halo 4 but seem to get a different type of error than I did last time I reached out.

Error extracting objects\weapons\pistol\storm_sticky_detonator\storm_sticky_detonator
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Adjutant.Blam.Common.BlockCollection`1.get_Item(Int32 index)
   at Adjutant.Blam.Halo4.Halo4Common.<GetMaterials>d__0.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Adjutant.Blam.Halo4.render_model.ReadGeometry(Int32 lod)
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IRenderGeometry geometry, String baseDir)
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IIndexItem tag)
   at CallSite.Target(Closure , CallSite , BatchExtractPlugin , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Reclaimer.Plugins.BatchExtractPlugin.Extract(Object tag, ExtractCounter counter)
Extracted 0 tags in 0 seconds with 1 errors.

Reclaimer is a super cool tool, I appreciate your absolute genius and will always respect you.

**Comment by Gravemind2401** [comment]
This should be resolved in the next update coming this week.
