### ISSUE TITLE
Halo Infinite module fails to open

### ISSUE THREAD

**Issue by Meowcat285** [Gravemind2401/Reclaimer#22]
First: Yes I know this tool isn't ment to open the Halo Infinite modules, but the format is similar and I was wondering if its possible to update it to open them. The error that occurs when opening it is below. Let me know if you need any more info

```Unable to load multiplayer_r1-rtx-new.module:
The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Adjutant.Blam.Halo5.ModuleItem.get_fileName()
   at Adjutant.Blam.Halo5.ModuleItem.get_ClassName()
   at Adjutant.Blam.Halo5.Module.TagIndex.ImportTags(IEnumerable`1 items)
   at Adjutant.Blam.Halo5.Module.TagIndex..ctor(IEnumerable`1 items)
   at Adjutant.Blam.Halo5.Module..ctor(String fileName, Module parentModule)
   at Reclaimer.Controls.ModuleViewer.LoadModule(String fileName)
   at Reclaimer.Plugins.ModuleViewerPlugin.OpenPhysicalFile(String fileName)```

**Comment by Gravemind2401** [comment]
Halo Infinite is now supported in the latest build.
