### ISSUE TITLE
Can't load Pelican interior from Halo 4

### ISSUE THREAD

**Issue by jbienz** [Gravemind2401/Reclaimer#23]
Can load other images, but not the interior diffuse or interior normal maps. Here's the error:

```
Loading image: objects\vehicles\human\storm_pelican\storm_pelican_interior\textures\pelican_interior_diff.bitmap
Error loading image: objects\vehicles\human\storm_pelican\storm_pelican_interior\textures\pelican_interior_diff.bitmap
System.InvalidOperationException: Data not found
   at Adjutant.Blam.Halo4.ResourceIdentifier.ReadData(PageType mode, Int32 maxLength)
   at Adjutant.Blam.Halo4.bitmap.ToDds(Int32 index)
   at Reclaimer.Controls.BitmapViewer.LoadImage(IBitmap image, String fileName)
   at Reclaimer.Plugins.BitmapViewerPlugin.DisplayBitmap(ITabContentHost targetWindow, IBitmap bitmap, String fileName)
```

**Comment by jbienz** [comment]
Turns out it couldn't read the textures from `m70_liftoff`, but it was able to read them from `m40_invasion`. I'm not sure why though.
