### ISSUE TITLE
scenario_structure_bsps from every MCC game except Reach don't load

### ISSUE THREAD

**Issue by Nukedrabbit95** [Gravemind2401/Reclaimer#38]
This might be the same issue as #35, but there were no details there so I'm just gonna open a new one.

What it says in the title. I've tried both viewing and extracting maps from CE, 3, ODST, Reach, and 4. Reach maps work fine. CE maps don't do anything at all (no output, no change in program). The rest all fail with the same exception:

```
Error loading model: [insert map here]
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Reclaimer.Blam.[Halo3/Halo4/Whatever].scenario_structure_bsp.ReadGeometry(Int32 lod)
   at Reclaimer.Controls.ModelViewer.SetLod(Int32 index) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Controls\ModelViewer.xaml.cs:line 107
   at Reclaimer.Controls.ModelViewer.LoadGeometry(IRenderGeometry geometry, String fileName) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Controls\ModelViewer.xaml.cs:line 102
   at Reclaimer.Plugins.ModelViewerPlugin.DisplayModel(ITabContentHost targetWindow, IRenderGeometry model, String fileName) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Plugins\ModelViewerPlugin.cs:line 117
```

When extracting, the exception is the same, but the location is not:

```
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IRenderGeometry geometry, String baseDir) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Plugins\BatchExtractPlugin.cs:line 427
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IExtractable item) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Plugins\BatchExtractPlugin.cs:line 409
   at Reclaimer.Plugins.BatchExtractPlugin.Extract(IExtractable item, ExtractCounter counter) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Plugins\BatchExtractPlugin.cs:line 282
```

**Comment by Gravemind2401** [comment]
Halo CE maps from MCC don't current have support for BSPs.
Halo 3 and up were no longer working after the MCC December update - this should now be resolved in Reclaimer v1.7.832.
