### ISSUE TITLE
Can't open Halo 3 .bsp after recent MCC update

### ISSUE THREAD

**Issue by Bl00df4rt** [Gravemind2401/Reclaimer#43]
It spits out this when trying to open one of the .bsp files for a map in Halo 3:

Loading model: levels\dlc\lockout\lockout.scenario_structure_bsp
Error loading model: levels\dlc\lockout\lockout.scenario_structure_bsp
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Reclaimer.Blam.Halo3.scenario_structure_bsp.ReadGeometry(Int32 lod)
   at Reclaimer.Controls.ModelViewer.SetLod(Int32 index) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Controls\ModelViewer.xaml.cs:line 107
   at Reclaimer.Controls.ModelViewer.LoadGeometry(IRenderGeometry geometry, String fileName) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Controls\ModelViewer.xaml.cs:line 102
   at Reclaimer.Plugins.ModelViewerPlugin.DisplayModel(ITabContentHost targetWindow, IRenderGeometry model, String fileName) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Plugins
   
I have ensured that I have all the necessary files like bink, mainmenu.map, etc. I'm a bit new to reclaimer and the update came out either yesterday or the day before, not sure. If I'm missing something, I'm more than happy to be pointed in the right direction because I've been trying to make this work for hours.

**Comment by Gravemind2401** [comment]
Usually when MCC is updated it will contain changes to the game files that mean Reclaimer will no longer recognize them, so Reclaimer needs to be updated to add support for those changes.

It has now been updated to support the recent MCC update: https://github.com/Gravemind2401/Reclaimer/releases/tag/v1.7.836
