### ISSUE TITLE
[Halo 5 Stuff Build] Batch-Extraction not working on H5 module due to Sequence containing no element

### ISSUE THREAD

**Issue by Zidiath** [Gravemind2401/Reclaimer#51]
When doing a batch extraction on Halo 5 Modules it fails off being unable to move past the initial extraction throwing the following error.

Also noted being unable to batch extract specific folders, that however does not throw an output. 

```
Error extracting levels\assets\osiris\props\mp_coliseum\coliseum_cover_001\coliseum_cover_001.render_model
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Max[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Reclaimer.Blam.Halo5.Halo5Common.GetMeshes(Halo5GeometryArgs args, List`1& materials) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer.Blam\Blam\Halo5\Halo5Common.cs:line 106
   at Reclaimer.Blam.Halo5.render_model.GetModelContent() in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer.Blam\Blam\Halo5\render_model.cs:line 116
   at Reclaimer.Blam.Halo5.render_model.GetContent() in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer.Blam\Blam\Halo5\render_model.cs:line 52
   at Reclaimer.Blam.Halo5.ContentTagDefinition`1.Reclaimer.Blam.Utilities.IContentProvider<TContent>.GetContent() in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer.Blam\Blam\Halo5\ContentTagDefinition.cs:line 25
   at Reclaimer.Plugins.ModelViewerPlugin.<>c.<.cctor>b__33_1(IContentProvider`1 model, String fileName) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\ModelViewerPlugin.cs:line 130
   at Reclaimer.Plugins.ModelViewerPlugin.WriteModelFile(IContentProvider`1 provider, String fileName, String formatId) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\ModelViewerPlugin.cs:line 183
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IContentProvider`1 provider, String baseDir) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\BatchExtractPlugin.cs:line 420
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IExtractable item) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\BatchExtractPlugin.cs:line 402
   at Reclaimer.Plugins.BatchExtractPlugin.Extract(IExtractable item, ExtractCounter counter) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\BatchExtractPlugin.cs:line 276
```

**Comment by Gravemind2401** [comment]
The batch extraction for module files should be working now after the latest commits.
