### ISSUE TITLE
[Halo 5 Stuff Build] Singleplayer Spartans are unable to be extracted

### ISSUE THREAD

**Issue by Zidiath** [Gravemind2401/Reclaimer#52]
```
Error extracting objects\characters\spartan_locke\spartan_locke.render_model
System.NullReferenceException: Object reference not set to an instance of an object.
   at Reclaimer.Geometry.CompatExtensions.WriteAMF(Model model, String fileName, Single scale) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer.Core\Geometry\Compat.cs:line 209
   at Reclaimer.Geometry.CompatExtensions.WriteAMF(Scene scene, String fileName, Single scale) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer.Core\Geometry\Compat.cs:line 56
   at Reclaimer.Plugins.ModelViewerPlugin.<>c.<.cctor>b__33_1(IContentProvider`1 model, String fileName) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\ModelViewerPlugin.cs:line 130
   at Reclaimer.Plugins.ModelViewerPlugin.WriteModelFile(IContentProvider`1 provider, String fileName, String formatId) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\ModelViewerPlugin.cs:line 183
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IContentProvider`1 provider, String baseDir) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\BatchExtractPlugin.cs:line 420
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IExtractable item) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\BatchExtractPlugin.cs:line 402
   at Reclaimer.Plugins.BatchExtractPlugin.Extract(IExtractable item, ExtractCounter counter) in O:\Games\Tools\Halo Tools\Recliamer-H5\Reclaimer-h5stuff\Reclaimer\Plugins\BatchExtractPlugin.cs:line 276
Extracted 0 tags in 0 seconds with 1 errors.
```

**Comment by Gravemind2401** [comment]
This should now be resolved.
