### ISSUE TITLE
Problem With some H2A Maps

### ISSUE THREAD

**Issue by TheMetroidThumper** [Gravemind2401/Reclaimer#55]
Maps such as bloodline can be opened and the scenario.structure.bsp viewable in the 3d viewer, but when I try to extract them (the model mind you, not the textures, those extract fine) one of two things will happen: If I'm extracting from the 3D viewer Reclaimer will CTD (if you've never played a bugthesda game that stands for Crash To Desktop) but if I try extracting it from the list (you know just right clicking on scenario.structure.bsp and selecting extract) then after around 37 seconds of it trying to do so I get this:

Error extracting levels\sway\ca_coagulation\ca_coagulation_bsp01.scenario_structure_bsp
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Reclaimer.Plugins.ModelViewerExtensions.CreateAssimpScene(IGeometryModel model, AssimpContext context, String formatId) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Plugins\ModelViewerPlugin.cs:line 464
   at Reclaimer.Plugins.ModelViewerPlugin.WriteModelFile(IGeometryModel model, String fileName, String formatId) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Plugins\ModelViewerPlugin.cs:line 199
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IRenderGeometry geometry, String baseDir) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Plugins\BatchExtractPlugin.cs:line 427
   at Reclaimer.Plugins.BatchExtractPlugin.SaveModel(IExtractable item) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Plugins\BatchExtractPlugin.cs:line 409
   at Reclaimer.Plugins.BatchExtractPlugin.Extract(IExtractable item, ExtractCounter counter) in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Plugins\BatchExtractPlugin.cs:line 282
Extracted 0 tags in 36 seconds with 1 errors.

Dafuq does that mean?! And why can't it be extracted even though it can be viewed?!

**Comment by Gravemind2401** [comment]
This should now be resolved in version 1.7.838.
